export const CONTACT_LISTALL_REQUEST = 'CONTACT_LISTALL_REQUEST'
export const CONTACT_LISTALL_SUCCESS = 'CONTACT_LISTALL_SUCCESS'
export const CONTACT_LISTALL_FAIL = 'CONTACT_LISTALL_FAIL'

export const CONTACT_DETAILS_REQUEST = 'CONTACT_DETAILS_REQUEST'
export const CONTACT_DETAILS_SUCCESS = 'CONTACT_DETAILS_SUCCESS'
export const CONTACT_DETAILS_FAIL = 'CONTACT_DETAILS_FAIL'

export const CONTACT_CREATE_REQUEST = 'CONTACT_CREATE_REQUEST'
export const CONTACT_CREATE_SUCCESS = 'CONTACT_CREATE_SUCCESS'
export const CONTACT_CREATE_FAIL = 'CONTACT_CREATE_FAIL'
